---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`necesita_saldo`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`cargar_bateria`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`tiene_bateria_maxima`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`tiene_bateria`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`apagar`"
  checked: false
name: Quiero entenderte
