---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Los números
  checked: true
- value: Los strings
  checked: true
- value: Los booleanos
  checked: true
- value: Las listas
  checked: true
- value: Los diccionarios
  checked: true
name: La verdad revelada
