---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`tiene_bateria_maxima`"
  checked: true
- value: "`tiene_bateria`"
  checked: false
- value: "`cargar_a_tope`"
  checked: true
- value: "`necesita_saldo`"
  checked: false
name: Interfaces compartidas
