---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
goal:
  kind: queries_match
  regexps:
  - "^bruno_diaz\\s+is\\s+batman\\s*$"
  - "^bruno_diaz\\s+is\\s+bruce_wayne\\s*$"
  - "^superman\\s+is\\s+clark_kent\\s*$"
  - "^superman\\s+is\\s+batman\\s*$"
name: El derecho a la identidad
